import type { Metadata } from "next";
import dynamic from "next/dynamic";
import "./globals.css";

import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";

const AuthProvider = dynamic(
  () => import("./components/contexts/auth-context")
);

export const metadata: Metadata = {
  title: "Quest - O seu jogo de perguntas e respostas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`bg-background-game min-h-screen px-2`}>
        <AuthProvider>{children}</AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
